export const KYB_DOCUMENT_TYPES = {
  ACTA_CONSTITUTIVA: "ACTA_CONSTITUTIVA",
  IDENTIFICACION_REPRESENTANTE: "IDENTIFICACION_REPRESENTANTE",
  PODER_REPRESENTANTE: "PODER_REPRESENTANTE",
  COMPROBANTE_DOMICILIO: "COMPROBANTE_DOMICILIO",
  RFC: "RFC",
  CONSTANCIA_SITUACION_FISCAL: "CONSTANCIA_SITUACION_FISCAL",
  MANIFESTACION_BAJO_PROTESTA: "MANIFESTACION_BAJO_PROTESTA",
  SOCIOS_ACCIONISTAS: "SOCIOS_ACCIONISTAS",
  BENEFICIARIO_CONTROLADOR: "BENEFICIARIO_CONTROLADOR",
} as const;

export const KYB_DECISIONS = {
  SAFE: "safe",
  REVIEW_REQUIRED: "review_required",
  HIGH_RISK: "high_risk",
} as const;

export const KYB_CASE_STATUS = {
  DRAFT: "draft",
  NEEDS_UPDATE: "needs_update",
  IN_REVIEW: "in_review",
  APPROVED: "approved",
  REJECTED: "rejected",
} as const;

export const RISK_RULES = {
  SAT_LIST_MATCH_CRITICAL: 100,
  SAT_LIST_MATCH_REVIEW: 60,
  MISSING_REQUIRED_DOCUMENT: 15,
  EXPIRED_DOCUMENT: 20,
  CSF_NOT_CURRENT_MONTH: 25,
  MATERIAL_DISCREPANCY: 30,
  FISCAL_LIST_REVIEW_OLDER_THAN_3_MONTHS: 20,
  INCOMPLETE_LEGAL_REPRESENTATIVE: 20,
  INCOMPLETE_SHAREHOLDERS_OR_BENEFICIAL_OWNER: 10,
} as const;